### ISSUE TITLE
How can I train my dataset? 

### ISSUE THREAD

**Issue by cwq63** [TACJu/TransFG#4]
Hello, thanks for your nice work!
My dataset have 10 classes,and each category is in a different folder.How can I train my dataset?

**Comment by cwq63** [comment]
thanks,w

**Comment by cwq63** [comment]
Thank you. I've taken care of it

**Comment by kihrgem** [comment]
> Thank you. I've taken care of it

Hello，could you share your code？
Thank you

**Comment by 895318** [comment]
> > Thank you. I've taken care of it
> 
> Hello，could you share your code？ Thank you

Hello, have you solved it on your own dataset? Can you share some code or ideas?
Thank you.
