### ISSUE TITLE
 visualization code

### ISSUE THREAD

**Issue by lao-ling-jie** [TACJu/TransFG#8]
Thanks for your wonderful work! I meet some problems when I try to visualize the part attention patch as your paper showed. So could you provide the visualization code. Thanks so much!
![image](https://user-images.githubusercontent.com/50287419/117235590-9a5c6180-ae59-11eb-9393-9a8ce47a008c.png)

**Comment by atoosachegini1** [comment]
were you able to visualize the attention parts?
I have some problems with this too.

**Comment by lao-ling-jie** [comment]
> were you able to visualize the attention parts?
> I have some problems with this too.

I visualized the attention parts by the index of the most important part of attention like paper writing. you can see the Part Selection code for help.

**Comment by 1844857130** [comment]
> Thanks for your wonderful work! I meet some problems when I try to visualize the part attention patch as your paper showed. So could you provide the visualization code. Thanks so much! ![image](https://user-images.githubusercontent.com/50287419/117235590-9a5c6180-ae59-11eb-9393-9a8ce47a008c.png)

您好，请问可以有偿向您请教下关于可视化的实现吗？
